version: '3'

services:
  app:
    build: .
    container_name: fastapi-usergamer
    ports:
      - 8000:8000
    command: bash -c "uvicorn TestProject.api.main:app --reload --host 0.0.0"

    volumes:
      - ./UserGamer.db:/app/UserGamer.db:delegated